### ISSUE TITLE
Problem of assembly 

### ISSUE THREAD

**Issue by hychen86** [nextgenusfs/FAC-assembly#3]
Hi Jon, 
Recently, I have an issue to run assemble_facs.py, the logfile is looks like this. Could you give me some suggestion, please! Thanks
Oct 14 10:26 AM] Running Python v2.7.18 
[Oct 14 10:26 AM] Loaded 259,098 PE reads
[Oct 14 10:26 AM] Trimming adapters from reads using Trim Galore
[Oct 14 10:26 AM] 258,505 PE reads passed quality trimming
Traceback (most recent call last):
  File "/home/seq/assemble_facs.py", line 178, in <module>
    download(url, acc_file)
  File "/home/seq/assemble_facs.py", line 44, in download
    u = urlopen(url)
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 502: Bad Gateway

**Comment by nextgenusfs** [comment]
It might just be a busy server -- if you run again and it keeps happening I can look.  We could put a retry on the download as well and/or link to a local download if necessary.

**Comment by hychen86** [comment]
> It might just be a busy server -- if you run again and it keeps happening I can look. We could put a retry on the download as well and/or link to a local download if necessary.

Thanks! Yes it's caused by the server. I try it today, it's fine!
